#!/usr/bin/env bash

SNOWSQL_ACCOUNT=hhezgea-ch79666
SNOWSQL_USER=MIKOLO777
SNOWSQL_DATABASE=TASTY_BYTES_SAMPLE_DATA
SNOWSQL_SCHEMA=RAW_POS
SNOWSQL_WAREHOUSE=compute_wh
sql_script=C:\\workspaces/snowdbtrep/exec.sql


snowsql -a $SNOWSQL_ACCOUNT -u $SNOWSQL_USER -d $SNOWSQL_DATABASE -s $SNOWSQL_SCHEMA -w $SNOWSQL_WAREHOUSE -p $SNOWSQL_PWD -f $sql_script

